
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqkerdduceeghlldjdvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxa2VyZGR1Y2VlZ2hsbGRqZHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mzc0MTEsImV4cCI6MjA1OTAxMzQxMX0.w_G30r8ld55JzVEKOzlhe2VIvoO1jQyYg7T5Yi2zxH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
